package com.suvan.demo.noplugin.mapper;

import com.suvan.demo.noplugin.model.Demo;
import com.suvan.demo.noplugin.model.DemoCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    long countByExample(DemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int deleteByExample(DemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int insert(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int insertSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    List<Demo> selectByExample(DemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    Demo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Demo record, @Param("example") DemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int updateByExample(@Param("record") Demo record, @Param("example") DemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int updateByPrimaryKeySelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Tue Jul 03 21:19:56 CST 2018
     */
    int updateByPrimaryKey(Demo record);
}