package com.suvan.demo.noplugin.model;

import com.suvan.mybatis.paging.model.BasePagingModel;

public class Demo extends BasePagingModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.updatetime
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.updatetime
     *
     * @return the value of demo.updatetime
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.updatetime
     *
     * @param updatetime the value for demo.updatetime
     *
     * @mbg.generated Sun Jul 01 19:20:08 CST 2018
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }
}